import type {Metadata} from "next";
import {Inter as FontSans} from "next/font/google"
import "./globals.css";
import {Providers} from "@/app/providers";
import {cn} from "@/lib/utils";
import {Header} from "@/app/header";

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
})
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
        <body
            className={cn(
                "min-h-screen bg-background font-sans antialiased bg-zinc-50 dark:bg-black",
                fontSans.variable
            )}
        >
        <main className="container mx-auto ring-1 ring-zinc-100 dark:ring-zinc-300/20 bg-white dark:bg-zinc-900 rounded-lg">
            <Providers>
                <Header/>
                {children}
            </Providers>
        </main>
        </body>
        </html>
    );
}
